version: '3.4'

services:
  catalog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  orders:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  ui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  yarp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    